// Regenerates supabase/migrations/0002_seed_program.sql from backend/data/program.json
// Usage: node backend/scripts/generate-seed.js
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..', '..');
const program = JSON.parse(readFileSync(resolve(root, 'backend/data/program.json'), 'utf8'));

const q = (v) => {
  if (v === null || v === undefined) return 'null';
  return `'${String(v).replace(/'/g, "''")}'`;
};
const qt = (v, first) => (v === null || v === undefined ? (first ? 'null::text' : 'null') : `${q(v)}${first ? '::text' : ''}`);

function inferLoggingMode(e) {
  if (e.loggingMode) return e.loggingMode;
  return e.tracksWeight ? 'weighted_sets' : 'completion_only';
}

function qJsonb(v, first) {
  if (v === null || v === undefined) return first ? 'null::jsonb' : 'null';
  return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
}

let out = `-- Seed the static program (idempotent). GENERATED by backend/scripts/generate-seed.js
-- Do not edit by hand; edit backend/data/program.json and regenerate.

begin;

delete from public.program_exercises;
delete from public.program_days;
`;

for (const day of program.days) {
  out += `\n-- Day ${day.dayNumber} — ${day.weekday} — ${day.title}\n`;
  out += `with d as (\n  insert into public.program_days (day_number, weekday, code, type, title, subtitle)\n  values (${day.dayNumber}, ${q(day.weekday)}, ${q(day.code)}, ${q(day.type)}, ${q(day.title)}, ${q(day.subtitle)})\n  returning id\n)\n`;
  out += `insert into public.program_exercises (day_id, sort_order, name, block, target_sets, target_reps, tracks_weight, is_priority, notes_hint, logging_mode, variant_options)\n`;
  out += `select d.id, v.sort_order, v.name, v.block, v.target_sets, v.target_reps, v.tracks_weight, v.is_priority, v.notes_hint, v.logging_mode, v.variant_options\nfrom d, (values\n`;
  const rows = day.exercises.map((e, i) => {
    const first = i === 0;
    const mode = inferLoggingMode(e);
    const variantOpts = e.variantOptions ?? null;
    return `  (${e.sortOrder}, ${q(e.name)}, ${first ? qt(e.block, true) : qt(e.block)}, ${first ? qt(e.targetSets, true) : qt(e.targetSets)}, ${first ? qt(e.targetReps, true) : qt(e.targetReps)}, ${e.tracksWeight}, ${e.isPriority}, ${first ? qt(e.notesHint, true) : qt(e.notesHint)}, ${q(mode)}, ${first ? qJsonb(variantOpts, true) : qJsonb(variantOpts)})`;
  });
  out += rows.join(',\n');
  out += `\n) as v(sort_order, name, block, target_sets, target_reps, tracks_weight, is_priority, notes_hint, logging_mode, variant_options);\n`;
}

out += `\ncommit;\n`;

writeFileSync(resolve(root, 'supabase/migrations/0002_seed_program.sql'), out);
console.log('Wrote supabase/migrations/0002_seed_program.sql');
