-- Seed the static program (idempotent). GENERATED by backend/scripts/generate-seed.js
-- Do not edit by hand; edit backend/data/program.json and regenerate.

begin;

delete from public.program_exercises;
delete from public.program_days;

-- Day 1 — monday — Lift A — Strength Pull
with d as (
  insert into public.program_days (day_number, weekday, code, type, title, subtitle)
  values (1, 'monday', 'lift_a', 'lift', 'Lift A — Strength Pull', 'Pull-up priority · Compound pulling · Lower body strength')
  returning id
)
insert into public.program_exercises (day_id, sort_order, name, block, target_sets, target_reps, tracks_weight, is_priority, notes_hint, logging_mode, variant_options)
select d.id, v.sort_order, v.name, v.block, v.target_sets, v.target_reps, v.tracks_weight, v.is_priority, v.notes_hint, v.logging_mode, v.variant_options
from d, (values
  (1, 'Pull-ups', null::text, '5'::text, '2–5'::text, false, true, 'Stop 1–2 reps before failure'::text, 'bodyweight_sets', null::jsonb),
  (2, 'Squat', null, '3', '5', true, false, null, 'weighted_sets', null),
  (3, 'Bench Press', null, '3', '5', true, false, null, 'weighted_sets', null),
  (4, 'Row', null, '3', '8–12', true, false, null, 'weighted_sets', null),
  (5, 'Bicep Curls', null, '2', '10–15', true, false, null, 'weighted_sets', null)
) as v(sort_order, name, block, target_sets, target_reps, tracks_weight, is_priority, notes_hint, logging_mode, variant_options);

-- Day 2 — tuesday — Movement 1 — Mobility & Recovery
with d as (
  insert into public.program_days (day_number, weekday, code, type, title, subtitle)
  values (2, 'tuesday', 'movement_1', 'movement', 'Movement 1 — Mobility & Recovery', 'Move well, recover, improve tissue quality · Intensity 5–6/10')
  returning id
)
insert into public.program_exercises (day_id, sort_order, name, block, target_sets, target_reps, tracks_weight, is_priority, notes_hint, logging_mode, variant_options)
select d.id, v.sort_order, v.name, v.block, v.target_sets, v.target_reps, v.tracks_weight, v.is_priority, v.notes_hint, v.logging_mode, v.variant_options
from d, (values
  (1, 'Jump rope', 'Warmup (5 min)'::text, null::text, '2 min'::text, false, false, null::text, 'completion_only', null::jsonb),
  (2, 'Arm circles', 'Warmup (5 min)', null, null, false, false, null, 'completion_only', null),
  (3, 'Hip circles', 'Warmup (5 min)', null, null, false, false, null, 'completion_only', null),
  (4, 'Light skipping', 'Warmup (5 min)', null, null, false, false, null, 'completion_only', null),
  (5, 'Deep squat hold', 'Block A — Mobility (15–20 min)', null, '60 sec', false, false, 'Flow continuously', 'completion_only', null),
  (6, 'World''s greatest stretch', 'Block A — Mobility (15–20 min)', null, '5/side', false, false, null, 'completion_only', null),
  (7, 'Couch stretch', 'Block A — Mobility (15–20 min)', null, '60 sec/side', false, false, null, 'completion_only', null),
  (8, 'Thoracic rotations', 'Block A — Mobility (15–20 min)', null, '8/side', false, false, null, 'completion_only', null),
  (9, 'Hanging from bar', 'Block A — Mobility (15–20 min)', '2', '30 sec', false, false, null, 'completion_only', null),
  (10, 'Ankle mobility rocks', 'Block A — Mobility (15–20 min)', null, '10/side', false, false, null, 'completion_only', null),
  (11, 'Bear crawl', 'Block B — Gymnastics Control (15–20 min)', '3', '20 yd', false, false, 'Low fatigue', 'completion_only', null),
  (12, 'Crab walk', 'Block B — Gymnastics Control (15–20 min)', '3', '20 yd', false, false, null, 'completion_only', null),
  (13, 'Hollow hold', 'Block B — Gymnastics Control (15–20 min)', '3', '30 sec', false, false, null, 'completion_only', null),
  (14, 'Arch hold', 'Block B — Gymnastics Control (15–20 min)', '3', '20 sec', false, false, null, 'completion_only', null),
  (15, 'Hanging knee raises', 'Block B — Gymnastics Control (15–20 min)', '3', '8', false, false, null, 'completion_only', null),
  (16, 'Light explosiveness (pick ONE)', 'Block C — Light Explosiveness (optional)', null, null, false, false, '5×20m sprints · or 5×3 box jumps · or 5×5 broad jumps', 'completion_only', null)
) as v(sort_order, name, block, target_sets, target_reps, tracks_weight, is_priority, notes_hint, logging_mode, variant_options);

-- Day 3 — wednesday — Lift B — Strength Push
with d as (
  insert into public.program_days (day_number, weekday, code, type, title, subtitle)
  values (3, 'wednesday', 'lift_b', 'lift', 'Lift B — Strength Push', 'Overhead pressing · Posterior chain · Lat work')
  returning id
)
insert into public.program_exercises (day_id, sort_order, name, block, target_sets, target_reps, tracks_weight, is_priority, notes_hint, logging_mode, variant_options)
select d.id, v.sort_order, v.name, v.block, v.target_sets, v.target_reps, v.tracks_weight, v.is_priority, v.notes_hint, v.logging_mode, v.variant_options
from d, (values
  (1, 'Overhead Press', null::text, '3'::text, '5'::text, true, false, null::text, 'weighted_sets', null::jsonb),
  (2, 'Romanian Deadlift', null, '3', '5', true, false, null, 'weighted_sets', null),
  (3, 'Incline DB Press', null, '3', '8–12', true, false, null, 'weighted_sets', null),
  (4, 'Lat Pulldown / Assisted Pull-ups', null, '3', '8–10', true, false, null, 'variant', '[{"key":"lat_pulldown","label":"Lat Pulldown","mode":"weighted_sets"},{"key":"assisted_pullups","label":"Assisted Pull-ups","mode":"bodyweight_sets"}]'::jsonb),
  (5, 'Core OR Dead Hang', null, '2–3', null, false, false, '2–3 sets', 'completion_only', null)
) as v(sort_order, name, block, target_sets, target_reps, tracks_weight, is_priority, notes_hint, logging_mode, variant_options);

-- Day 4 — thursday — Movement 2 — Speed, Power & Agility
with d as (
  insert into public.program_days (day_number, weekday, code, type, title, subtitle)
  values (4, 'thursday', 'movement_2', 'movement', 'Movement 2 — Speed, Power & Agility', 'Speed, power, agility · Quality > fatigue · Intensity 6–7/10')
  returning id
)
insert into public.program_exercises (day_id, sort_order, name, block, target_sets, target_reps, tracks_weight, is_priority, notes_hint, logging_mode, variant_options)
select d.id, v.sort_order, v.name, v.block, v.target_sets, v.target_reps, v.tracks_weight, v.is_priority, v.notes_hint, v.logging_mode, v.variant_options
from d, (values
  (1, 'A-skips', 'Warmup (10 min)'::text, null::text, null::text, false, false, null::text, 'completion_only', null::jsonb),
  (2, 'B-skips', 'Warmup (10 min)', null, null, false, false, null, 'completion_only', null),
  (3, 'High knees', 'Warmup (10 min)', null, null, false, false, null, 'completion_only', null),
  (4, 'Carioca', 'Warmup (10 min)', null, null, false, false, null, 'completion_only', null),
  (5, 'Dynamic lunges', 'Warmup (10 min)', null, null, false, false, null, 'completion_only', null),
  (6, 'Box jumps', 'Block A — Plyometrics (15 min)', '5', '3', false, false, 'Quality > fatigue', 'completion_only', null),
  (7, 'Lateral bounds', 'Block A — Plyometrics (15 min)', '3', '6/side', false, false, null, 'completion_only', null),
  (8, 'Depth drops', 'Block A — Plyometrics (15 min)', '3', '5', false, false, null, 'completion_only', null),
  (9, 'Agility (choose 2)', 'Block B — Agility (15 min)', null, null, false, false, 'Shuttle 5-10-5 ×5 · Cone drill ×5 · Reaction drill ×10 · Fast feet ×5 rounds', 'completion_only', null),
  (10, 'Fun finisher', 'Block C — Fun (10–15 min)', null, null, false, false, 'Find a workout online you want to try — go for it!', 'completion_only', null)
) as v(sort_order, name, block, target_sets, target_reps, tracks_weight, is_priority, notes_hint, logging_mode, variant_options);

-- Day 5 — friday — Lift C — Pull-up Progression + Legs
with d as (
  insert into public.program_days (day_number, weekday, code, type, title, subtitle)
  values (5, 'friday', 'lift_c', 'lift', 'Lift C — Pull-up Progression + Legs', 'EMOM pull-up volume · Leg strength · Upper body balance')
  returning id
)
insert into public.program_exercises (day_id, sort_order, name, block, target_sets, target_reps, tracks_weight, is_priority, notes_hint, logging_mode, variant_options)
select d.id, v.sort_order, v.name, v.block, v.target_sets, v.target_reps, v.tracks_weight, v.is_priority, v.notes_hint, v.logging_mode, v.variant_options
from d, (values
  (1, 'Pull-ups — EMOM', null::text, '10 min'::text, '1–3/min'::text, false, true, '1–3 reps every minute for 10 min'::text, 'bodyweight_sets', null::jsonb),
  (2, 'Front Squat', null, '3', '5', true, false, null, 'weighted_sets', null),
  (3, 'Bulgarian Split Squat', null, '3', '8', true, false, null, 'weighted_sets', null),
  (4, 'Chest-Supported Row', null, '3', '10', true, false, null, 'weighted_sets', null),
  (5, 'Hand Release Push-ups', null, '2–3', null, false, false, '2–3 sets', 'completion_only', null)
) as v(sort_order, name, block, target_sets, target_reps, tracks_weight, is_priority, notes_hint, logging_mode, variant_options);

commit;
